name: geoloc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_map: ^4.0.0
  flutter_native_splash: ^2.2.16
  flutter_polyline_points: ^1.0.0

  freezed_annotation: ^2.2.0
  google_maps_flutter: ^2.2.5
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  location: ^4.4.0
  permission_handler: ^10.2.0
  scroll_to_index: ^3.0.1
  table_calendar: ^3.0.8

dev_dependencies:

  build_runner:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_native_splash:
  image: "assets/images/bg.png"
  color: "000000"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
